import React from 'react';
import './PrivacyPolicy.css';
import Header from '../components/Header';
import Footer from '../components/Footer';

const PrivacyPolicy = () => {
  return (
    <>
      <Header />  
      
      <div className="privacy-policy-container">
        <h1>Privacy Policy</h1>
        <p>Updated at 2024-05-08</p>
        <p>
          Quick Vision Studios (“we”, “our” or “us”) is committed to protecting your privacy. This Privacy Policy explains how your personal information is collected, used, and disclosed by Quick Vision Studios.
        </p>
        <p>
          This Privacy Policy applies to our website, https://quvi.ai, and its associated subdomains (collectively, our “Service”). By accessing or using our Service, you signify that you have read, understood, and agree to our collection, storage, use, and disclosure of your personal information as described in this Privacy Policy and our Terms of Service.
        </p>

        <h2>Definitions and key terms</h2>
        <p>
          To help explain things as clearly as possible in this Privacy Policy, every time any of these terms are referenced, are strictly defined as:
        </p>
        <ul>
          <li><strong>Cookie</strong>: small amount of data generated by a website and saved by your web browser. It is used to identify your browser, provide analytics, remember information about you such as your language preference or login information.</li>
          <li><strong>Company</strong>: when this policy mentions “Company”, “we”, “us”, or “our”, it refers to Quick Vision Studios that is responsible for your information under this Privacy Policy.</li>
          <li><strong>Country</strong>: where Quick Vision Studios or the owners/founders of Quick Vision Studios are based, in this case is Türkiye.</li>
          <li><strong>Customer</strong>: refers to the company, organization or person that signs up to use the Quick Vision Studios Service to manage the relationships with your consumers or service users.</li>
          <li><strong>Device</strong>: any internet connected device such as a phone, tablet, computer or any other device that can be used to visit Quick Vision Studios and use the services.</li>
          <li><strong>IP address</strong>: every device connected to the Internet is assigned a number known as an Internet protocol (IP) address. These numbers are usually assigned in geographic blocks. An IP address can often be used to identify the location from which a device is connecting to the Internet.</li>
          <li><strong>Personnel</strong>: refers to those individuals who are employed by Quick Vision Studios or are under contract to perform a service on behalf of one of the parties.</li>
          <li><strong>Personal Data</strong>: any information that directly, indirectly, or in connection with other information — including a personal identification number — allows for the identification or identifiability of a natural person.</li>
          <li><strong>Service</strong>: refers to the service provided by Quick Vision Studios as described in the relative terms (if available) and on this platform.</li>
          <li><strong>Third-party service</strong>: refers to advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you.</li>
          <li><strong>Website</strong>: Quick Vision Studios’s site, which can be accessed via this URL: https://quvi.ai.</li>
          <li><strong>You</strong>: a person or entity that is registered with Quick Vision Studios to use the Service.</li>
        </ul>

        <h2>What Information Do We Collect?</h2>
        <p>
          We collect information from you when you visit our service, register, place an order, subscribe to our newsletter, respond to a survey or fill out a form.
        </p>
        <ul>
          <li>Name / Username</li>
          <li>Email Address</li>
        </ul>

        <h2>How Do We Use The Information We Collect?</h2>
        <p>Any of the information we collect from you may be used in one of the following ways:</p>
        <ul>
          <li>To personalize your experience (your information helps us to better respond to your individual needs)</li>
          <li>To improve our service (we continually strive to improve our service offerings based on the information and feedback we receive from you)</li>
          <li>To improve customer service (your information helps us to more effectively respond to your customer service requests and support needs)</li>
          <li>To process transactions</li>
          <li>To administer a contest, promotion, survey or other site feature</li>
          <li>To send periodic emails</li>
        </ul>

        <h2>When Do We Use Customer Information From Third Parties?</h2>
        <p>
          We receive some information from the third parties when you contact us. For example, when you submit your email address to us to show interest in becoming our customer, we receive information from a third party that provides automated fraud detection services to us. We also occasionally collect information that is made publicly available on social media websites. You can control how much of your information social media websites make public by visiting these websites and changing your privacy settings.
        </p>

        <h2>Do We Share The Information We Collect With Third Parties?</h2>
        <p>
          We may share the information that we collect, both personal and non-personal, with third parties such as advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you. We may also share it with our current and future affiliated companies and business partners, and if we are involved in a merger, asset sale or other business reorganization, we may also share or transfer your personal and non-personal information to our successors-in-interest.
        </p>
        <p>
          We may engage trusted third party service providers to perform functions and provide services to us, such as hosting and maintaining our servers and our service, database storage and management, e-mail management, storage marketing, credit card processing, customer service and fulfilling orders for products and services you may purchase through our service. We will likely share your personal information, and possibly some non-personal information, with these third parties to enable them to perform these services for us and for you.
        </p>

       

      </div>

      <Footer />  {/* Footer componentini ekleyin */}
    </>
  );
};

export default PrivacyPolicy;
