// src/pages/TermsOfUse.jsx
import React from 'react';
import Footer from '../components/Footer'
import Header from '../components/PagesHeader';
import './TermsOfUse.css';

const TermsOfUse = () => {
  return (
    <div className="terms-container">
      <Header />
      <div className="terms-content">
        <h1>Terms & Conditions</h1>
        <p>Updated at 2024-05-06</p>

        <h2>General Terms</h2>
        <p>
          By accessing and placing an order with Quick Vision Studios, you confirm that you are in agreement with and bound by the terms of service contained in the Terms & Conditions outlined below...
        </p>

        <h2>License</h2>
        <p>
          Quick Vision Studios grants you a revocable, non-exclusive, non-transferable, limited license to download, install and use the website strictly in accordance with the terms of this Agreement...
        </p>

        <h2>Definitions and key terms</h2>
        <ul>
          <li><strong>Cookie:</strong> Small amount of data generated by a website and saved by your web browser...</li>
          <li><strong>Company:</strong> When this policy mentions “Company,” “we,” “us,” or “our,” it refers to Quick Vision Studios...</li>
          <li><strong>Country:</strong> Where Quick Vision Studios is based, in this case, Türkiye...</li>
          <li><strong>Customer:</strong> Refers to the company, organization or person that signs up to use the Quick Vision Studios Service...</li>
          <li><strong>Device:</strong> Any internet-connected device that can be used to visit Quick Vision Studios and use the services...</li>
          <li><strong>IP address:</strong> Every device connected to the Internet is assigned a number known as an Internet protocol (IP) address...</li>
          <li><strong>Personnel:</strong> Refers to those individuals who are employed by Quick Vision Studios...</li>
          <li><strong>Personal Data:</strong> Any information that directly or indirectly allows for the identification of a natural person...</li>
          <li><strong>Service:</strong> Refers to the service provided by Quick Vision Studios as described in the relative terms...</li>
          <li><strong>Third-party service:</strong> Refers to advertisers, contest sponsors, promotional and marketing partners...</li>
          <li><strong>Website:</strong> Quick Vision Studios’s site, which can be accessed via this URL: quvi.ai...</li>
          <li><strong>You:</strong> A person or entity that is registered with Quick Vision Studios to use the Services...</li>
        </ul>

        <h2>Restrictions</h2>
        <p>
          You agree not to, and you will not permit others to...
        </p>

        <h2>Payment</h2>
        <p>
          If you pay for any of our one-time payment plans, you agree to pay all fees or charges to your account...
        </p>

        <h2>Return and Refund Policy</h2>
        <p>
          Thanks for shopping with us. We appreciate the fact that you like to buy the stuff we build...
        </p>

        <h2>Your Suggestions</h2>
        <p>
          Any feedback, comments, ideas, improvements, or suggestions (collectively, “Suggestions”) provided by you...
        </p>

        <h2>Your Consent</h2>
        <p>
          We’ve updated our Terms & Conditions to provide you with complete transparency...
        </p>

        <h2>Links to Other Websites</h2>
        <p>
          Our service may contain links to other websites that are not operated by Us...
        </p>

        <h2>Cookies</h2>
        <p>
          We use “Cookies” to identify the areas of our website that you have visited...
        </p>

        <h2>Changes To Our Terms & Conditions</h2>
        <p>
          You acknowledge and agree that we stop (permanently or temporarily) providing the Service...
        </p>

        <h2>Modifications to Our Service</h2>
        <p>
          We reserve the right to modify, suspend or discontinue, temporarily or permanently...
        </p>

        <h2>Updates to Our Service</h2>
        <p>
          We may from time to time provide enhancement or improvements to the features...
        </p>

        <h2>Third-Party Services</h2>
        <p>
          We may display, include or make available third-party content...
        </p>

        <h2>Term and Termination</h2>
        <p>
          This Agreement shall remain in effect until terminated by you or us...
        </p>

        <h2>Copyright Infringement Notice</h2>
        <p>
          If you are a copyright owner or such owner’s agent and believe any material from us constitutes an infringement...
        </p>

        <h2>Indemnification</h2>
        <p>
          You agree to indemnify and hold us and our parents, subsidiaries, affiliates, officers, employees...
        </p>

        <h2>No Warranties</h2>
        <p>
          The service is provided to you “AS IS” and “AS AVAILABLE” and with all faults and defects without warranty...
        </p>

        <h2>Limitation of Liability</h2>
        <p>
          Notwithstanding any damages that you might incur, the entire liability of us and any of our suppliers...
        </p>

        <h2>Severability</h2>
        <p>
          If any provision of this Agreement is held to be unenforceable or invalid...
        </p>

        <h2>Waiver</h2>
        <p>
          Except as provided herein, the failure to exercise a right or to require performance...
        </p>

        <h2>Amendments to this Agreement</h2>
        <p>
          We reserve the right, at its sole discretion, to modify or replace this Agreement...
        </p>

        <h2>Entire Agreement</h2>
        <p>
          The Agreement constitutes the entire agreement between you and us regarding your use of the service...
        </p>

        <h2>Updates to Our Terms</h2>
        <p>
          We may change our Service and policies, and we may need to make changes to these Terms...
        </p>

        <h2>Intellectual Property</h2>
        <p>
          Our platform and its entire contents, features and functionality are owned by us, its licensors...
        </p>

        <h2>Agreement to Arbitrate</h2>
        <p>
          This section applies to any dispute except it doesn’t include a dispute relating to claims for injunctive or equitable relief...
        </p>

        <h2>Notice of Dispute</h2>
        <p>
          In the event of a dispute, you or us must give the other a Notice of Dispute...
        </p>

        <h2>Binding Arbitration</h2>
        <p>
          If you and us don’t resolve any dispute by informal negotiation...
        </p>

        <h2>Submissions and Privacy</h2>
        <p>
          In the event that you submit or post any ideas, creative suggestions, designs...
        </p>

        <h2>Promotions</h2>
        <p>
          We may, from time to time, include contests, promotions, sweepstakes, or other activities...
        </p>

        <h2>Typographical Errors</h2>
        <p>
          In the event a product and/or service is listed at an incorrect price...
        </p>

        <h2>Miscellaneous</h2>
        <p>
          If for any reason a court of competent jurisdiction finds any provision...
        </p>

        <h2>Disclaimer</h2>
        <p>
          We are not responsible for any content, code, or any other imprecision...
        </p>

        <h2>Contact Us</h2>
        <p>
          Don’t hesitate to contact us if you have any questions.<br />
          - Via Email: quickvisionai@gmail.com
        </p>

        <p>Quick Vision Studios 2024. All Rights Reserved.</p>
      </div>
      <Footer />
    </div>
  );
};

export default TermsOfUse;
